# Notebook 4: Numpy

In this section we will introduce you to the `numpy` package; one of the most widely-used and fundamental packages in Python. It is likely you will use `numpy` a lot when working in Python. This is a recommended notebook for anyone who has not used Python before.

**Note:** Often, by convention `numpy` is commonly aliased as `np`.

In [1]:
import numpy as np

### Table of Contents

 - [Notebook 0: Introduction](./nb_00_introduction.ipynb)
 - [Notebook 1: Datatypes, loops and logic](./nb_01_datatypes_loops_and_logic.ipynb)
 - [Notebook 2: Functions, modules and packages](./nb_02_functions_modules_and_packages.ipynb)
 - [Notebook 3: Managing files](./nb_03_managing_files.ipynb)
 - [**Notebook 4: Numpy**](./nb_04_numpy.ipynb)
   - [Introduction](#Introduction)
   - [numpy basics](#numpy-basics)
     - [Array Attributes and Methods](#Array-Attributes-and-Methods)
     - [Loading arrays from text files](#Loading-arrays-from-text-files)
     - [Reshaping and Transposing arrays](#Reshaping-and-Transposing-arrays)
     - [Concatenating arrays](#Concatenating-arrays)
   - [Operating on arrays](#Operating-on-arrays)
     - [Scalar operations](#Scalar-operations)
     - [Matrix multiplication](#Matrix-multiplication)
   - [Broadcasting](#Broadcasting)
   - [Linear algebra](#Linear-algebra)
   - [Random Numbers in numpy](#Random-Numbers-in-numpy)
   - [Array Indexing](#Array-Indexing)
     - [Indexing multi-dimensional arrays](#Indexing-multi-dimensional-arrays)
     - [Coordinate array indexing](#Coordinate-array-indexing)
     - [Boolean indexing](#Boolean-indexing)
   - [Getting Help](#Getting-Help)
   
   
   
 - [Notebook 5: Pandas](./nb_05_pandas.ipynb)
 - [Notebook 6: Scipy](./nb_06_scipy.ipynb)
 - [Notebook 7: Plotting and images](./nb_07_plotting_and_images.ipynb)

## Introduction

`numpy`'s main role in the Python ecosystem is to provide crucial support for scientific computing. It does this by introducing a new datatype; the `array` (or more specifically the `ndarray`; the n-dimensional array). We can create a numpy array from a python list using the `array` function like so:

In [2]:
# This is a Python list 
example_list = [1,2,3]
print(example_list)

# This is a numpy array
example_array = np.array(example_list)
print(example_array)

[1, 2, 3]
[1 2 3]


On the face of it, the `list` and the `array` look very similar; **however**, for scientific computing a numpy array is much (much, much, much) more efficient for scientific than the standard Python list.


 > **RECAP:** When performing scientific/numerical computation you should use numpy arrays, not Python lists! 

This often seems strange and causes confusion for new Python users; after all why would the standard data type for mathematical computing not be in-built in Python? The, perhaps strange seeming, truth is that in Python more often than not you will be using Python packages that are not in-built. This is just the way Python works - don't be daunted by the thought of having to import all your modules - this is perfectly normal and acceptable in the world of Python!

## `numpy` basics

Many `numpy` functions have extremely intuitive syntax and strongly resemble corresponding functions in the `Matlab` language. For example;

In [3]:
print('np.zeros produces an array of zeros:')
print(np.zeros(3))
print('-----------------------------------------')
print('np.ones gives an array of ones:')
print(np.ones(3))
print('-----------------------------------------')
print('np.arange gives a range of values:')
print(np.arange(2,7))
print('-----------------------------------------')
print('np.linspace gives N linearly spaced numbers:')
print(np.linspace(0, 1, 5))
print('-----------------------------------------')
print('np.eye gives us an identity matrix:')
print(np.eye(3))
print('-----------------------------------------')
print('np.diag gives us a diagonal matrix:')
print(np.diag([9, 8, 7]))
print('-----------------------------------------')


np.zeros produces an array of zeros:
[0. 0. 0.]
-----------------------------------------
np.ones gives an array of ones:
[1. 1. 1.]
-----------------------------------------
np.arange gives a range of values:
[2 3 4 5 6]
-----------------------------------------
np.linspace gives N linearly spaced numbers:
[0.   0.25 0.5  0.75 1.  ]
-----------------------------------------
np.eye gives us an identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-----------------------------------------
np.diag gives us a diagonal matrix:
[[9 0 0]
 [0 8 0]
 [0 0 7]]
-----------------------------------------


### Array Attributes and Methods


The `array` has many attributes that are often useful to know, several of which are given in the example below:

In [4]:
example_array = np.array([1,-2,3])
print('example array:')
print(example_array)
print('======================================')
print('shape:')
print(example_array.shape)
print('--------------------------------------')
print('data type*:')
print(example_array.dtype)
print('--------------------------------------')
print('size (number of elements):')
print(example_array.size)
print('--------------------------------------')
print('number of dimensions:')
print(example_array.ndim)
print('--------------------------------------')
print('number of bytes taken up by the array:')
print(example_array.nbytes)
print('--------------------------------------')

example array:
[ 1 -2  3]
shape:
(3,)
--------------------------------------
data type*:
int64
--------------------------------------
size (number of elements):
3
--------------------------------------
number of dimensions:
1
--------------------------------------
number of bytes taken up by the array:
24
--------------------------------------


 > **\* Note:** Elements in an `array` are saved as `numpy` data types rather than in-built Python data types. In the above example, for instance, the values in `example_array` are saved as `numpy` `int64` objects rather than Python `int`s (check this using the `type` function). To learn more about the `numpy` datatypes see the [numpy documentation here](https://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html). This is worth bearing in mind should you get any strange data type based errors.

The `array` also has many convenient methods (a `method` is just a Python way saying "function which belongs to a specific object"). For example:

In [5]:
example_array = np.array([1,-2,4,0,0,2,0,10])
print('example array:')
print(example_array)
print('======================================')
print('minimum:')
print(example_array.min())
print('--------------------------------------')
print('maximum:')
print(example_array.max())
print('--------------------------------------')
print('index of minimum:')
print(example_array.argmin())  
print('--------------------------------------')
print('index of maximum:')
print(example_array.argmax())  
print('--------------------------------------')
print('mean:')
print(example_array.mean())
print('--------------------------------------')
print('variance:')
print(example_array.var())
print('--------------------------------------')
print('standard deviation:')
print(example_array.std())
print('--------------------------------------')
print('sum:')
print(example_array.sum())
print('--------------------------------------')
print('product:')
print(example_array.prod())
print('--------------------------------------')


example array:
[ 1 -2  4  0  0  2  0 10]
minimum:
-2
--------------------------------------
maximum:
10
--------------------------------------
index of minimum:
1
--------------------------------------
index of maximum:
7
--------------------------------------
mean:
1.875
--------------------------------------
variance:
12.109375
--------------------------------------
standard deviation:
3.4798527267687636
--------------------------------------
sum:
15
--------------------------------------
product:
0
--------------------------------------


These methods can also be applied to multi-dimensional arrays. For example;

In [6]:
example_array = np.array([[1,2,3,4],[0,3,4,1]])
print('example array:')
print(example_array)
print('======================================')
print('overall minimum:')
print(example_array.min())
print('--------------------------------------')
print('row minimums:')
print(example_array.min(axis=1))
print('--------------------------------------')
print('column minimums:')
print(example_array.min(axis=0))
print('--------------------------------------')
print('Overall Minimum index:')
print(example_array.argmin())
print('--------------------------------------')
print('Row minimum indices:')
print(example_array.argmin(axis=1))
print('--------------------------------------')
print('Column minimum indices:')
print(example_array.argmin(axis=0))
print('--------------------------------------')

example array:
[[1 2 3 4]
 [0 3 4 1]]
overall minimum:
0
--------------------------------------
row minimums:
[1 0]
--------------------------------------
column minimums:
[0 2 3 1]
--------------------------------------
Overall Minimum index:
4
--------------------------------------
Row minimum indices:
[0 0]
--------------------------------------
Column minimum indices:
[1 0 0 1]
--------------------------------------


 > **Note:** For multi-dimensional arrays, the `argmin` and `argmax` methods will return the index of the minimum/maximum values for a flattened view of the array. 
>
> For example, in the above `0` is the minimum value. If we read across rows and then down columns then we can see that `0` would be the 5th element we would read. As Python uses zero indexing this would mean that the element `0` has index `4`, which explains the "Overall minimum index" in the above output.

### Loading arrays from text files

We can load numpy arrays from text files using the `loadtxt` function.

In [7]:
example = np.loadtxt('04_numpy/example_data.txt')
print(example)

[[1.  0.  0. ]
 [0.  2.  3.4]]


We can also write to a text file using the `savetxt` function.

In [15]:
data = np.array([[1,0,0],[0,1,0],[0,0,2.3]])
np.savetxt('04_numpy/data_we_just_saved.txt', data, delimiter=',')

Have a look at the file `data_we_just_saved.txt` file and make sure you understand how the above code works. You may notice the file is strangely formatted. You can change this using the [`fmt` argument in the `savetxt` function](http://docs.scipy.org/doc/numpy/reference/generated/numpy.savetxt.html).

In [13]:
np.savetxt('04_numpy/data_we_just_saved.txt', data, delimiter=' ', fmt='%.3e')

After changing the format and saving, try loading the arraay again.

In [14]:
data = np.loadtxt('04_numpy/data_we_just_saved.txt')
data

array([[1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 2.3]])

### Reshaping and Transposing arrays

A `numpy` `array` can be reshaped using the `reshape` method. For example;


In [18]:
example_array = np.arange(12)
print('Array: \n', example_array)
print('Array shape: ',example_array.shape)

print('--------------------------------------')

reshaped = np.array(example_array.reshape((3,4)))
print('Reshaped: \n', reshaped)
print('New shape: ',reshaped.shape)

print('--------------------------------------')

reshaped = np.array(example_array.reshape((2,3,2)))
print('Reshaped Again: \n', reshaped)
print('New shape: ',reshaped.shape)

Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Array shape:  (12,)
--------------------------------------
Reshaped: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New shape:  (3, 4)
--------------------------------------
Reshaped Again: 
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
New shape:  (2, 3, 2)


 > **Note:** Reshaping an array only creates another view of an array object. To create a new copy of the array the `np.array` constructor must be used, like in the above. For more information on the dangers of creating multiple references to the same object, please read the `copying and references` section of Notebook 1. An illustrative example is also given below.

In [22]:
id(reshaped) == id(example_array)

False

In [29]:
# Lets look at what happens if we don't use the np array operator
example_array = np.arange(12)
print('Array: \n', example_array)
print('--------------------------------------')

# We reshape the array (with no np.array operator)
reshaped = example_array.reshape((3,4))
print('Reshaped array: \n', reshaped)
print('--------------------------------------')

# We change a value in the reshaped array
reshaped[2,0]=100
print('Changed reshaped array: \n', reshaped)
print('--------------------------------------')

# And the original array has also chaged
print('Original array also changed: \n', example_array)

Array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
--------------------------------------
Reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------------------------
Changed reshaped array: 
 [[  0   1   2   3]
 [  4   5   6   7]
 [100   9  10  11]]
--------------------------------------
Original array also changed: 
 [  0   1   2   3   4   5   6   7 100   9  10  11]


Arrays can be transposed with the `T` attribute or `transpose` method like so:

In [33]:
example_array = np.arange(12).reshape((3,4))

print(example_array)
print(example_array.T)
print(example_array.transpose())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


Note, both `T` and `transpose` do not change the array, they return a transposed array.

For higher dimensional arrays we can think of transposing an array as simply switching the order of the axes. This is exactly what is happening in the below. Try this out for yourself to make sure you understand what is happening here. 

In [34]:
example_array = np.arange(12).reshape((3,2,2))

# Print the array
print(example_array)
print('\n-----------------------\n')
# Swap the last two axes and print again
print(example_array.transpose((0,2,1)))

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]

-----------------------

[[[ 0  2]
  [ 1  3]]

 [[ 4  6]
  [ 5  7]]

 [[ 8 10]
  [ 9 11]]]


### Concatenating arrays

You can join together, or concatenate, several numpy arrays with the numpy `concatenate` function. If you specify an axis, it will concatenate it along that axis; otherwise it will default to concatenation along the `0`th axis.

In [35]:
zero_array = np.zeros((2, 3))
one_array = np.ones((2, 3))

print('Column-wise concatenation:')
print(np.concatenate((zero_array, one_array), axis=1))

print('Row-wise concatenation:')
print(np.concatenate((zero_array, one_array), axis=0))

print('(Default) Row-wise concatenation:')
print(np.concatenate((zero_array, one_array)))


Column-wise concatenation:
[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
Row-wise concatenation:
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
(Default) Row-wise concatenation:
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]


The `hstack`, `vstack` and `dstack` functions also perform array concatenation along the first, second, or third dimension respectively:

In [37]:
zero_array = np.zeros((2, 3))
one_array = np.ones((2, 3))

# Stack on first dimension (Horizontally)
hstacked = np.hstack((zero_array, one_array)) # axis=1 in concatenate
print('hstacked shape: ', hstacked.shape)
print('hstacked:')
print( hstacked)
print('--------------------------------------------')

# Stack on second dimension (Vertically)
vstacked = np.vstack((zero_array, one_array)) # axis=0 in concatenate
print('vstacked shape: ', vstacked.shape)
print('vstacked:')
print( vstacked)
print('--------------------------------------------')

# Stack on third dimension (Add a dimention)
dstacked = np.dstack((zero_array, one_array)) # axis=2 in concatenate
print('dstacked shape: ', dstacked.shape)
print('dstacked:')
print( dstacked)

hstacked shape:  (2, 6)
hstacked:
[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
--------------------------------------------
vstacked shape:  (4, 3)
vstacked:
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
--------------------------------------------
dstacked shape:  (2, 3, 2)
dstacked:
[[[0. 1.]
  [0. 1.]
  [0. 1.]]

 [[0. 1.]
  [0. 1.]
  [0. 1.]]]


## Operating on arrays

`numpy` provides a wide and powerful range of operations you can perform on arrays. However, especially if you are coming from having previously worked in different languages, some of the syntax might not be completely ituitive.

### Scalar operations

All of the standard mathematical operators in Python also exist in `numpy`.

In [38]:
example_array = np.arange(1, 10).reshape((3, 3))
print('example_array:')
print(example_array)
print('example_array + 2:')
print( example_array + 2)
print('example_array * 3:')
print( example_array * 3)
print('example_array ** 3:')
print( example_array ** 3)
print('example_array % 2:')
print( example_array % 2)


example_array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
example_array + 2:
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
example_array * 3:
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
example_array ** 3:
[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]
example_array % 2:
[[1 0 1]
 [0 1 0]
 [1 0 1]]


 > **Note**: Again, in Python exponentiation is performed with the `**` operator and not the `^`! Do not fall for this trap!

In [39]:
print('example_array ^ 3:')
print( example_array ^ 3)

example_array ^ 3:
[[ 2  1  0]
 [ 7  6  5]
 [ 4 11 10]]


 > **Note**: If you have worked in `matlab` previous you may be used to using the `*` operator for matrix multiplication. Be careful here as, as we saw above, in Python **\* is elementwise not matrix** multiplication.

### Matrix multiplication

In Python, matrix multiplication can be performed with the `@` symbol. This feature is pretty new in Python and if you are working in older versions of python you may wish to use the `matmul` or `dot` functions:

In [43]:
a = np.arange(9).reshape(3,3)
b = np.arange(3,12).reshape(3,3)
print('a \n', a)
print('b \n', b)

print('@ operator: \n', a @ b)

print('dot function: \n', a.dot(b))

print('matmul function: \n', np.matmul(a,b))

a 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
b 
 [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
@ operator: 
 [[ 24  27  30]
 [ 78  90 102]
 [132 153 174]]
dot function: 
 [[ 24  27  30]
 [ 78  90 102]
 [132 153 174]]
matmul function: 
 [[ 24  27  30]
 [ 78  90 102]
 [132 153 174]]


 > **Note:** We reiterate, in Python matrix multiplication is done with the `@` operator, not the `*` operator! `numpy` does have an alternative datatype called the `matrix` which follows more matlab-like conventions; however, we will not cover that here as the `numpy` `array` is a much more developed and well-maintained datatype.

## Broadcasting

One of the most powerful and important tools to know about in `numpy` is *broadcasting*. Broadcasting allows you to perform arithmetic operations on arrays with different shapes to one another. Given two numpy arrays, for each axis in the two arrays, numpy will implicitly expand the shape of the smaller axis to match the shape of the larger one. This may become clearer with a few examples.

 > **Note:** Those who are familiar with recent versions matlab may know `broadcasting` as `implicit expansion`.

For arrays of a low dimension, broadcasting has many uses. For example, you could add the elements of a 1D vector to all of the rows or columns of a 2D array:

In [48]:
a = np.arange(9).reshape((3, 3))
b = np.array([[1,0,2]])
print('a \n', a)
print('b \n', b, '\n')

print('a + b (row-wise): \n', a + b, '\n')

print('a + b.T (column-wise): \n', a + b.T)

a 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
b 
 [[1 0 2]] 

a + b (row-wise): 
 [[ 1  1  4]
 [ 4  4  7]
 [ 7  7 10]] 

a + b.T (column-wise): 
 [[ 1  2  3]
 [ 3  4  5]
 [ 8  9 10]]


This is an extremely powerful tool. For example, we could use it to demean (i.e. subtract the mean from each column) a 2d array like so:

In [51]:
example_array = np.arange(9).reshape((3, 3))
print('example_array:')
print(example_array)

print('example_array (cols demeaned):')
# .mean(axis=0) calculates (means across all rows <=> means for each of the columns)
print(example_array - example_array.mean(axis=0))

example_array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
example_array (cols demeaned):
[[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]


In higher dimensions this is also extremely useful. Say for instance we have three, 2 by 2 numpy arrays and from each array we wish to subtract the 2 x 2 identity matrix. We could do this like so:

In [52]:
# Make 3 2 by 2 matrices
example_array = np.arange(12).reshape(3,2,2)
print('example_array')
print(example_array)

print('\nidentity matrix')
print(np.eye(2))

# Subtract identity
print('\nexample_array-identity')
print(example_array-np.eye(2))

example_array
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]

identity matrix
[[1. 0.]
 [0. 1.]]

example_array-identity
[[[-1.  1.]
  [ 2.  2.]]

 [[ 3.  5.]
  [ 6.  6.]]

 [[ 7.  9.]
  [10. 10.]]]


Broadcasting is an extremely powerful tool and can be used in many more situations than those we have discussed above. It can be confusing at first but we strongly recommend you take the time to understand and work through as much information about broadcasting as you can. Broadcasting will make your code much cleaner and potentially **much** faster. To learn more see the [`numpy` broadcasting documentation](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html).

## Linear algebra

Numpy provides a range of linear algebra and matrix functions. Most of these functions live in the `linalg` module.

In [54]:
import numpy.linalg as npla

Below are a few examples of some `numpy` linear algebra functions. The syntax for these functions should seem fairly intuitive and full documentation can be found [here](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html).

In [55]:
example_array = np.array([[1, 0, 2],
                          [3, 2, 6],
                          [0, 5, 8]])
print('example_array')
print(example_array)

print('example_array determinant')
print(npla.det(example_array))

print('example_array rank')
print(npla.matrix_rank(example_array))

print('example_array inverse')
print(npla.inv(example_array))

print('example_array qr decomposition')
print(npla.qr(example_array))

example_array
[[1 0 2]
 [3 2 6]
 [0 5 8]]
example_array determinant
16.000000000000007
example_array rank
3
example_array inverse
[[-8.7500000e-01  6.2500000e-01 -2.5000000e-01]
 [-1.5000000e+00  5.0000000e-01  4.4408921e-17]
 [ 9.3750000e-01 -3.1250000e-01  1.2500000e-01]]
example_array qr decomposition
(array([[-0.31622777,  0.11905137,  0.94118371],
       [-0.9486833 , -0.03968379, -0.3137279 ],
       [-0.        , -0.99209474,  0.12549116]]), array([[-3.16227766, -1.8973666 , -6.32455532],
       [ 0.        , -5.03984127, -7.9367579 ],
       [ 0.        ,  0.        ,  1.00392929]]))


 > **Warning:** As can be seen in the above example, `numpy` functions, just like any other pieces of code, are not infallible and are prone to machine error. In our example, we know that the determinant should be `16` but in this case `numpy` has very slightly underestimated it. Bear this in mind if you ever start seeing very small numerical differences in your results.

## Random Numbers in `numpy`

Another useful feature in `numpy` we will briefly mention here is the `random` module which allows you to generate random numbers. Some examples of how this works are given below but the full documentation can be found [here](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html).

In [61]:
import numpy.random

print('Standard normal random sample:')
print(np.random.randn(4), '\n')

print('Uniform sample of integers between 0 and 9:')
print(np.random.randint(10,size=4), '\n')

print('Binomial (10, 0.2) random sample:')
print(np.random.binomial(10,0.2,size=4), '\n')

Standard normal random sample:
[ 0.10614075 -0.34159751  1.16682676 -0.39393517] 

Uniform sample of integers between 0 and 9:
[2 8 8 2] 

Binomial (10, 0.2) random sample:
[1 3 2 1] 



## Array Indexing

`numpy` arrays support a wide range of useful and convenient indexing features including those supported in standard Python. To get started, lets look at a one-dimensional array. We can index a one-dimensional `numpy` array in all the same ways we could index the Python `list` (see notebook 1 for more details on indexing the Python `list`).

In [63]:
example_array = np.arange(8)

print('example_array:                  ', example_array)
print('first element:                  ', example_array[0])
print('first three elements:           ', example_array[:3])
print('last element (using shape):     ', example_array[example_array.shape[0] - 1])
print('last element (using -1 index):  ', example_array[-1])
print('last three elements:            ', example_array[-3:])
print('middle two elements:            ', example_array[3:5])
print('Every second element:           ', example_array[1::2])
print('Every second element, reversed: ', example_array[-1::-2])

example_array:                   [0 1 2 3 4 5 6 7]
first element:                   0
first three elements:            [0 1 2]
last element (using shape):      7
last element (using -1 index):   7
last three elements:             [5 6 7]
middle two elements:             [3 4]
Every second element:            [1 3 5 7]
Every second element, reversed:  [7 5 3 1]


 > **Warning:** Again we have a mutability-based issue here. Indexing only creates a view into an array; not a copy! See the below for an example of the dangers here. For more information see the **Important: Copying and references** section of notebook 1.

In [64]:
# Here is an example array
example_array = np.arange(8)

# Here are 3 elements from that array
threeElements = example_array[2:5]
print(threeElements)

# We now change an element in the original array
example_array[4] = -9

# And our `threeElements` array has also changed!
print(threeElements)

# To overcome this, use the np.array function to make
# a copy rather than a reference
threeElements = np.array(example_array[2:5])

[2 3 4]
[ 2  3 -9]


### Indexing multi-dimensional arrays

Multidimensional array indexing in Python can be performed much in the same way as for a one-dimensional array. The only difference is now we have expressions for indices in each dimension. The syntax for this is to seperate indices by commas. For example;

In [69]:
example_array = np.arange(16).reshape((4, 4))
print('example_array:')
print(example_array)
print('-----------------------------------------')
print('First row:')
print(example_array[  0, :])
print('-----------------------------------------')
print('Last row:')
print(example_array[ -1, :])
print('-----------------------------------------')
print('Second and third columns: ')
print(example_array[:, 1:3])
print('-----------------------------------------')
print('2 by 2 sub-block:')
print(example_array[0:2, 0:2])

example_array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
-----------------------------------------
First row:
[0 1 2 3]
-----------------------------------------
Last row:
[12 13 14 15]
-----------------------------------------
Second and third columns: 
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
-----------------------------------------
2 by 2 sub-block:
[[0 1]
 [4 5]]


 > **Warning:** Again watch out for mutability problems and remember we are using zero indexing!
 
 > **Note:** The syntax to access a the `(i,j)`th element in a `list` is 
 > - `listname[i][j]` 
 >
 > Whereas for an `array` the syntax is: 
   - `arrayname[i,j]`. 
 >
 > This can be confusing at first but remember, in general for scientific computing it is better to use the `array`. You will probably find you use the `list` syntax a lot less frequently than the `array` syntax.

You can also use ellipses, i.e. `...`, to return all elements from all remaining dimensions. E.g.

In [72]:
example_array = np.arange(12).reshape((2, 2, 3))
print(example_array)
print('------------------------------')

# This gives all elements which have index zero in 
# the first dimension (equivalent to example_array[0,:,:]
# in this case)
print(example_array[0, ...])
print('------------------------------')

# This gives all elements which have index one in 
# the last dimension (equivalent to example_array[:,:,1]
# in this case)
print(example_array[..., 1])
print('------------------------------')

# This gives all elements which have index one in 
# the first dimension and index two in the last 
# dimension (equivalent to example_array[1,:,2]
# in this case)
print(example_array[1, ..., 2])
print('------------------------------')

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
------------------------------
[[0 1 2]
 [3 4 5]]
------------------------------
[[ 1  4]
 [ 7 10]]
------------------------------
[ 8 11]
------------------------------


### Coordinate array indexing

`numpy` also allows you to use lists or other `numpy` arrays as indices! This is an extremely useful feature as it allows us to return all sorts of subsets of an array. For example;

In [73]:
# Example array
example_array = np.arange(16).reshape((4, 4))
print('example_array:')
print(example_array)
print('-----------------------------------------')

# Make some row and column coordinates
row = [1,2,0]
col = [2,3,1]
print('Here are some elements we selected:')
print(example_array[row,col])
print('-----------------------------------------')

# Get diagonal elements (note we can use a list
# or numpy array for the row/column indices!)
row = np.array([0,1,2,3]) 
col = np.array([0,1,2,3])
print('Here are the diagonal elements:')
print(example_array[row,col])
print('-----------------------------------------')

# Get anti-diagonal elements 
row = np.array([0,1,2,3]) 
col = np.array([3,2,1,0])
print('Here are the anti-diagonal elements:')
print(example_array[row,col])
print('-----------------------------------------')


example_array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
-----------------------------------------
Here are some elements we selected:
[ 6 11  1]
-----------------------------------------
Here are the diagonal elements:
[ 0  5 10 15]
-----------------------------------------
Here are the anti-diagonal elements:
[ 3  6  9 12]
-----------------------------------------


 > **Warning:** It may be tempting to think that the syntax `1:4` is the same as using the list `[0,1,2,3]`. However, there are subtle differences. 
 >
 > For example `array[1:4,1:4]` will give the 4 by 4 sub-block of an array whilst `array[[0,1,2,3],[0,1,2,3]]` will give you only the first 4 diagonal elements. Some good practical advice is to print out your arrays as you write code to check you are definitely indexing the elements you think you are indexing.

A related useful function is the `numpy.where` function. This gives us a list of indices for all elements in an array where a boolean condition is true. For example;

In [74]:
# Example array
example_array = np.arange(16).reshape((4, 4))
print('example_array:')
print(example_array)
print('-----------------------------------------')

rows, cols = np.where(example_array>10)
print('row indices of example elements with value > 10:')
print(rows)
print('column indices of example elements with value > 10:')
print(cols)

example_array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
-----------------------------------------
row indices of example elements with value > 10:
[2 3 3 3 3]
column indices of example elements with value > 10:
[3 0 1 2 3]


The `numpy.where` function can be combined with array indexing to give us all values in an `array` which satisfy a certain condition. For example, we could return all the elements of an array whose square is less than `20` like so:

In [76]:
# Example array
example_array = np.arange(16).reshape((4, 4))
print('example_array:')
print(example_array)
print('-----------------------------------------')

print('elements whose square is less than 20:')
print(example_array[np.where(example_array**2<20)])

example_array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
-----------------------------------------
elements whose square is less than 20:
[0 1 2 3 4]


Often, however, it is easier and more direct to use boolean indexing.

### Boolean indexing

We can index a `numpy` `array` directly with a boolean array of the same shape. For example:

In [77]:
example_array = np.arange(8)

print('example_array:')
print(example_array)
print('example_array > 4:')
print(example_array > 4)
print('elements in example_array that are > 4:')
print(example_array[example_array > 4])

example_array:
[0 1 2 3 4 5 6 7]
example_array > 4:
[False False False False False  True  True  True]
elements in example_array that are > 4:
[5 6 7]


 > **Note:** Unlike in the previous sections on indexing, Boolean indexing **does** return a copy of the original array as opposed to just another view/reference of the object. For example:

In [80]:
example_array = np.arange(8)

print('example_array:')
print(example_array)

# Get the elements less than 4
less_than_four = example_array[example_array < 4]
print('elements in example_array that are < 4:')
print(less_than_four)

# Change an element in the original array
example_array[1]=200

print('example_array changed:')
print(example_array)

# Our result did not change this time!
print('less_than_four did not change')
print(less_than_four)


example_array:
[0 1 2 3 4 5 6 7]
elements in example_array that are < 4:
[0 1 2 3]
example_array changed:
[  0 200   2   3   4   5   6   7]
less_than_four did not change
[0 1 2 3]


You can also use the `all` and `any` functions to assess whether all elements satisfy a condition or any elements satisfy a condition respectively (much like the existential and universal quantifiers in first order logic).

In [82]:
# Make a 3 by 3 array of random normal variables
x = np.random.randn(3,4)
print(x)

# Check if all values are greater than -1.5
print('\nAll > -1.5:')
print(np.all(x>-1.5))

# Check if any values are greater than 1.5
print('\nAny > 1.5:')
print(np.any(x>1.5))

# Check if all values in each row are greater than -1.5
print('\nAll in each row > -1.5:')
print(np.all(x>-1.5,axis=1))

# Check if any values in each column are greater than 1.5
print('\nAny in each column > 1.5:')
print(np.any(x>1.5,axis=0))


[[ 0.45256754  0.20221925  0.00708885 -0.1320274 ]
 [ 1.02698398 -0.97442333  0.8086001   1.06434095]
 [ 0.5241043  -0.10874396  0.80981441 -0.01499026]]

All > -1.5:
True

Any > 1.5:
False

All in each row > -1.5:
[ True  True  True]

Any in each column > 1.5:
[False False False False]


## Getting Help

This notebook aims to give a basic understanding of some of the most commonly used `numpy` functions. However, there is much more to learn and you will likely always find yourself looking for documentation. For more information on `numpy` features, see the [documentation here](https://docs.scipy.org/doc/numpy/user/index.html) or use the help function like below.

In [83]:
help(np.kron)

Help on function kron in module numpy:

kron(a, b)
    Kronecker product of two arrays.
    
    Computes the Kronecker product, a composite array made of blocks of the
    second array scaled by the first.
    
    Parameters
    ----------
    a, b : array_like
    
    Returns
    -------
    out : ndarray
    
    See Also
    --------
    outer : The outer product
    
    Notes
    -----
    The function assumes that the number of dimensions of `a` and `b`
    are the same, if necessary prepending the smallest with ones.
    If `a.shape = (r0,r1,..,rN)` and `b.shape = (s0,s1,...,sN)`,
    the Kronecker product has shape `(r0*s0, r1*s1, ..., rN*SN)`.
    The elements are products of elements from `a` and `b`, organized
    explicitly by::
    
        kron(a,b)[k0,k1,...,kN] = a[i0,i1,...,iN] * b[j0,j1,...,jN]
    
    where::
    
        kt = it * st + jt,  t = 0,...,N
    
    In the common 2-D case (N=1), the block structure can be visualized::
    
        [[ a[0,0]*b,   a[0,

# Exercises

**Question 1:** In the file `triangle.txt` you will find a list of [triangular numbers](https://en.wikipedia.org/wiki/Triangular_number). Load this file in as a numpy array using the `np.loadtxt` function. You will notice that the array is a strange shape. Save the original shape of the array as a variable in your workspace and then reshape the array into a row vector.

In [84]:
%ls

02_functions_modules_and_packages/
03_managing_files/
04_numpy/
05_pandas/
06_scipy/
07_plotting_and_images/
nb_00_introduction.ipynb
nb_01_datatypes_loops_and_logic.ipynb
nb_02_functions_modules_and_packages.ipynb
nb_03_managing_files.ipynb
nb_04_numpy.ipynb
nb_05_pandas.ipynb
nb_06_scipy.ipynb
nb_07_plotting_and_images.ipynb


In [112]:
# Write your code here
tria_original = np.loadtxt('./04_numpy/triangle.txt')
tria_original

array([[  1.,   3.,   6.],
       [ 10.,  15.,  21.],
       [ 28.,  36.,  45.],
       [ 55.,  66.,  78.],
       [ 91., 105., 120.],
       [136., 153., 171.],
       [190., 210., 231.],
       [253., 277., 300.],
       [325., 351., 378.],
       [406., 435., 465.],
       [496., 528., 561.],
       [595., 630., 666.]])

In [113]:
tria_original.shape

(12, 3)

In [114]:
tria_reshaped = tria_original.reshape(-1,)
tria_reshaped

array([  1.,   3.,   6.,  10.,  15.,  21.,  28.,  36.,  45.,  55.,  66.,
        78.,  91., 105., 120., 136., 153., 171., 190., 210., 231., 253.,
       277., 300., 325., 351., 378., 406., 435., 465., 496., 528., 561.,
       595., 630., 666.])

In [115]:
ns = np.arange(1, len(tria_reshaped)+1)
Tns = ns * (ns+1) / 2
Tns

array([  1.,   3.,   6.,  10.,  15.,  21.,  28.,  36.,  45.,  55.,  66.,
        78.,  91., 105., 120., 136., 153., 171., 190., 210., 231., 253.,
       276., 300., 325., 351., 378., 406., 435., 465., 496., 528., 561.,
       595., 630., 666.])

In [118]:
print(Tns[tria_reshaped != Tns], 'should be placed instead of', tria_reshaped[tria_reshaped != Tns], 'at index 22')
# np.where(tria_reshaped != Tns)

[276.] should be placed instead of [277.] at index 22


In [119]:
tria_reshaped[tria_reshaped != Tns] = Tns[tria_reshaped != Tns]
tria_reshaped

array([  1.,   3.,   6.,  10.,  15.,  21.,  28.,  36.,  45.,  55.,  66.,
        78.,  91., 105., 120., 136., 153., 171., 190., 210., 231., 253.,
       276., 300., 325., 351., 378., 406., 435., 465., 496., 528., 561.,
       595., 630., 666.])

One of the values in the array is incorrect. See if you can work out which value it is and replace it in your array. You will need the formula for a triangle number;

$T(n) = \frac{n(n+1)}{2}$

*Extra challenge: Save the triangular numbers back to `triangle.txt` in integer format (i.e. without any decimal points. You may need the [numpy documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.savetxt.html) for this.)*

In [127]:
# Write your code here
np.savetxt(fname='./04_numpy/triangle_new.txt', X=tria_reshaped, fmt='%i') # d or i : signed decimal integer 

**Question 2:** Using array broadcasting, demean and rescale all the columns of the below numpy array (i.e. subtract the mean from each column and then divide each column by it's standard deviation). Print the new mean and standard deviation of each column to demonstrate your code worked. *Hint: look at the previous sections for help with this.*

In [132]:
# Matrix to demean
X = np.random.randn(100,10)

# Write your code here
X = X - X.mean(axis=0)
X = X / X.std(axis=0)

print(X.mean(axis=0).round(5))
print(X.std(axis=0))

[-0.  0. -0.  0. -0.  0.  0.  0.  0.  0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Now, by transposing, demean and rescale `X` *row-wise*.

In [ ]:
# Write your code here

**Question 3:** Write a function, `divisors`, which given an integer $k$, returns a numpy array of all [divisors](https://en.wikipedia.org/wiki/Divisor) of $k$. *Hint: The `%` operator may be useful here*.

In [ ]:
def divisors(k):
    
    # Write your code here

# Example 
print(divisors(100)) # Should give [  1   2   4   5  10  20  25  50 100]

**Question 4:** Write a function which as input takes in a square matrix (in numpy array format) of arbitrary size and transforms it into a vector of each of the columns of the matrix stacked on top of one another. For example, given a matrix of the below form, your function should return a column vector like so:

$$\begin{bmatrix} a & b & c \\ d & e & f \\ g & h & i \\\end{bmatrix} \rightarrow \begin{bmatrix} a \\ d \\ g \\ b \\ e \\ h \\ c \\ f \\ i \end{bmatrix}$$.

In [ ]:
def mat2vec(matrix):
  
  # Write your function here

# Use this example to test your code
matrix = np.random.randn(3,3)
print(matrix)
print(mat2vec(matrix))

Now, write a function which does the reverse. I.e. your fuction should take as input a vector of size $k^2$ by 1, for some arbitrary integer $k$, and return a $k$ by $k$ matrix such that the original vector is each of the columns of the matrix stacked on top of one another. 

For example, given a vector of the below form, your function should return a matrix like so:

$$\begin{bmatrix} a \\ d \\ g \\ b \\ e \\ h \\ c \\ f \\ i \end{bmatrix} \rightarrow \begin{bmatrix} a & b & c \\ d & e & f \\ g & h & i \\\end{bmatrix}$$.

In [ ]:
def vec2mat(matrix):
  
  # Write your function here

# Use this example to test your code
vec = np.array([[1,2,3,4]]).transpose()
mat = vec2mat(vec)
print(vec)
print(mat)

As a final test, check that running `vec2mat` followed by `mat2vec` on a numpy array of appropriate size gives the same numpy array you started with:

In [ ]:
print(vec2mat(mat2vec(matrix))==matrix)
print(mat2vec(vec2mat(vec))==vec)

**Question 5 (hard):** Assume in this question that, for simplicity, that $X$, $A$, $B$ and $C$ are all square matrices of size $n$ by $n$. The [Lyapunov Equation](https://www.math.uwaterloo.ca/~hwolkowi/matrixcookbook.pdf) tells us the following: if we have a matrix equation of the form;

$AX + XB = C$

Then it can be rearranged to obtain $X$ in the following way:

$\text{vec}(X) = (I \otimes A + B^T \otimes I)^{-1}\text{vec}(C)$

Where;
 - $\otimes$ is the [kronecker product](https://en.wikipedia.org/wiki/Kronecker_product).
 - $I$ is the $n$ by $n$ identity matrix.
 - `vec` represents the vec operator, which performs the same operation as the `mat2vec` function we wrote in question 4.
 
Write a function, `lyapunov`, which, given $A$, $B$ and $C$ as numpy arrays returns $X$ as a numpy array. You will need the following functions;
 - [`np.linalg.inv`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html?highlight=inv#numpy.linalg.inv): This inverts a matrix.
 - [`np.eye`](docs.scipy.org/doc/numpy/reference/generated/numpy.eye.html?highlight=eye#numpy.eye): This gives an identity matrix of a specified size, e.g. `np.eye(3)` gives the 3 by 3 identity matrix.
 - [`np.kron`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.kron.html#numpy.kron): This gives the kronecker product of two matrices, i.e. `np.kron(A,B)`=$A \otimes B$
 - The `mat2vec` and `vec2mat` functions you wrote in question 4.

In [ ]:
def lyapunov(A,B,C):
    
    # Write your function here

# Example for you to test on; random A B and X
A = np.random.randn(5,5)
B = np.random.randn(5,5)
X = np.random.randn(5,5)

# Work out C
C = A @ X + X @ B

# Check if your output looks like the X we used!
print('Our calculated X:')
print(lyapunov(A,B,C))
print('The true X:')
print(X)